steps:
  - name: "bash"
    args: ["./prebuild.sh"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/ledoxide:latest", "--cache-from", "gcr.io/${PROJECT_ID}/ledoxide:latest", "."]
    env:
      - "DOCKER_BUILDKIT=1"
images:
  - "gcr.io/$PROJECT_ID/ledoxide:latest"
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
